### ISSUE TITLE
Sometimes setting up a dispenser at 0.009 ends up with 0.00899999 and similar

### ISSUE THREAD

**Issue by TashaMoon** [jdogresorg/freewallet-desktop#102]
Sometimes setting up a dispenser at rounded amount t ex 0.009 ends up with one satoshi less dispenser (0.00899999) and similar.

Also it case of this error SOME (2 buyers of 14).  buyers experience one satoshi distraction from their BTC send to the dispenser resulting in no card dispense.

**Comment by jdogresorg** [comment]
Similar issue to #110 which has been fixed and will be included in the next release.
