### ISSUE TITLE
display of asset quantity for assets that have subassets

### ISSUE THREAD

**Issue by mdw** [jdogresorg/freewallet-desktop#106]
In FreeWallet desktop version 0.9.22 an asset that has subassets seems to show a "Total Supply" quantity of zero and an "unlocked" icon for the parent asset in the detail panel.

![parent-asset-supply-bug](https://user-images.githubusercontent.com/28559/199053766-530b0195-c0a4-4e92-813e-8ba0595dd55b.png)

**Comment by jdogresorg** [comment]
this issue should be fixed in the next release.
