### ISSUE TITLE
capitalization error for lowercase subasset names in multisend

### ISSUE THREAD

**Issue by mdw** [jdogresorg/freewallet-desktop#107]
When constructing a multisend, Freewallet (version 0.9.22) auto-capitalizes the asset name for me, so I can be sloppy with mixing case. 

But when parsing my list of sends, it seems to NOT capitalize the subasset names however, resulting in an error. It's already allowing me the luxury of entering in lowercase assetnames, so the desirable behavior would be to capitalize all and throw no error.

![subasset-lowercase-mpma](https://user-images.githubusercontent.com/28559/199067453-c8f647be-3bf8-4ba8-8055-aaf480869464.png)

**Comment by jdogresorg** [comment]
Subassets names can contain lower and upper case characters, so forcing subassets to all caps is not a viable option.

I believe the behavior that your seeing now in freewallet is the correct behavior, where an error is thrown if you enter an asset name incorrectly.

You should be sure to enter your asset/subasset names exactly as it is registered, as all of these subasset names below are valid names.

ASSET.one
ASSET.One
ASSET.ONE
ASSET.OnE
ASSET.ONe
.... etc

Each of the above subassets are valid subasset names, so forcing the subasset name to upper case (ie, ASSET.ONE) would prevent one from being able to send some of the other valid subasset names

**Comment by mdw** [comment]
TIL - thanks!
