### ISSUE TITLE
autocomplete in sensitive text fields

### ISSUE THREAD

**Issue by loon3** [jdogresorg/freewallet-desktop#108]
Autocomplete should be disabled in any sensitive text field (private key, passphrase, password) to prevent the unnecessary caching of data.

**Comment by jdogresorg** [comment]
Disabled on 12-word passphrase field
https://github.com/jdogresorg/freewallet-desktop/blob/master/html/passphrase-existing.html#L3

Disabled on password & confirm password fields
https://github.com/jdogresorg/freewallet-desktop/blob/master/js/freewallet-desktop.js#L3632-L3634

Disabled on import private key
https://github.com/jdogresorg/freewallet-desktop/blob/master/js/freewallet-desktop.js#L3775

Disabled on 'Passphrase' field in settings screen
https://github.com/jdogresorg/freewallet-desktop/blob/master/html/settings.html#L40

I believe this should cover all the 'sensitive' fields. If you think of any others that I have overlooked, please let me know. :)

This update will be in the next release.
