### ISSUE TITLE
Freewallet underpays 1 satoshi

### ISSUE THREAD

**Issue by kirillkovalenko** [jdogresorg/freewallet-desktop#110]
Dispenser: https://xchain.io/tx/fbceb330ac936295145321a29437a71b0f571035ba2c45d0c473b5c6001629cc 29999 sats

TX1: https://mempool.space/tx/0dd8bc30040990d0318f964e26fcf25bfe453082379554828ae7a925da1ec340 (1 sat underpaid)
TX2: https://mempool.space/tx/f8246cd7ebe612ed5897fb8c82d9fcaab7409b49aca137e6d7db13a66fcf2e24 (1 sat underpaid)

**Comment by kirillkovalenko** [comment]
TX3: https://mempool.space/tx/1c3236f03bb8635f0e63a7ad07d2115192eb36d5ca7c08a3e9092db195aec933 (1 sat)
TX4: https://mempool.space/tx/763e2da5d3d1858d5ebc5600a987eda3fc278b570aa931055310f7a1eaca95a4 (1 sat)

**Comment by jdogresorg** [comment]
issue should be fixed in the next FreeWallet release. Closing issue
