### ISSUE TITLE
Missing addresses in freewallet desktop 

### ISSUE THREAD

**Issue by dhayor01** [jdogresorg/freewallet-desktop#120]
Hi. I imported my counterparty wallet into freewallet desktop. I opened two dispensers using the address generated in the wallet. I tried sending out funds but was getting errors, updated the app but I can’t find the addresses anymore.

**Comment by jdogresorg** [comment]
this is not the place for support. This is a place to report technical issues with the wallet with technical details.

If you have a question about frewallet, please ask your question in the Counterparty telegram room and allow the community members to answer your questions.

https://t.me/Counterparty_XCP
