### ISSUE TITLE
Exchange inputs editing bug

### ISSUE THREAD

**Issue by Skept0x** [jdogresorg/freewallet-desktop#125]
Editing inputs glitch when editing numbers >= 1,000.000 on DEX (All inputs).

![FreeWallet_kyyZa5picw](https://user-images.githubusercontent.com/131699410/235302726-d5d8621d-e2ea-4782-8785-a0ef917e374e.gif)

**Comment by davestaxcp** [comment]
This can be confusing at first, but I tried my best to explain why this is auto filled and the best way to input Buy and Sell Orders on the DEx here in this draft of the Freewallet FAQ: https://gist.github.com/davestaxcp/1e2cc086a13c9a2d045876852b57e5be#buying-and-selling-xcp-and-tokens-on-the-dex

**Comment by jdogresorg** [comment]
Cleaned up numeric value and parsing with commit https://github.com/jdogresorg/freewallet-desktop/commit/d1297ebea5ccfac792b37b4f1029e028ac97f398
