### ISSUE TITLE
cannot send transaction, insufficient balance error

### ISSUE THREAD

**Issue by luboremo** [jdogresorg/freewallet-desktop#129]
Freewallet version 0.9.23 on Windows 11

trying to send lock transaction -> error:
"""
Error composing issuance transaction via API: Insufficient BTC at address <address>. (Need approximately <float> BTC.) To spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)
"""

the wallet has 10x that amount of BTC that is needed for the transaction.

**Comment by jdogresorg** [comment]
this is an error that comes directly from Counterparty, not freewallet specific.
