### ISSUE TITLE
Import the mnemonic of free wallet to sparrow wallet issue

### ISSUE THREAD

**Issue by sslisen** [jdogresorg/freewallet-desktop#131]
Import the mnemonic of free wallet to sparrow wallet, but the displayed address is different, and the path setting cannot be found in free wallet.
How can I import the address of free wallet into sparrow wallet.

**Comment by jdogresorg** [comment]
The derivation path in Counterparty wallets is different than other wallets. 

I am not familiar with sparrow wallet. Please ask questions about sparrow wallet to the sparrow wallet team.
