### ISSUE TITLE
Failover API for sending broadcasts is deprecated every time i send a large TX, or large multisend I cant send it.

### ISSUE THREAD

**Issue by Iheff** [jdogresorg/freewallet-desktop#137]
https://github.com/jdogresorg/freewallet-desktop/pull/136
suppied a Pull Request that resolves this issue - needs a small local test before deployment as I havent treid building the whole thing.

**Comment by jdogresorg** [comment]
merged your pull request in... it should be in the next wallet release coming out next week :)
