### ISSUE TITLE
Donate Button vs ADS Choices

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#146]
Why does the Donate button on FreeWallet "About" popup go to 1FWDonkMbC6hL64JiysuggHnUAw2CKWszs. 
Could this explained a little more with some text if going to Freewallet Dev instead of an instant popup to a tx?

Would it be a better to add choices to also point to the different Funds or ongoing CIP's as shown on the Automatic Donations page in Settings? Even there I think more links to education of what each fund is and what they represent at the present moment can help a lot. This may be the first time a user finds out what a CIP is.

I think more education on how to donate to Freewallet vs Counterparty initiatives could be helpful if giving the user to see what and why they are donating and specifically to who.

**Comment by jdogresorg** [comment]
The auto-donation system is separate from the "Donate" button on the about page.

If a user wants to just "donate" to freewallet, independent of the ADS, then they should be able to do so, as has been in the past.

Also, please only open github issues for actual technical issues, not for suggestions or feature requests, that belongs in the "Discussions" section.
