### ISSUE TITLE
Freewallet Dark Mode & Custom Themes

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#148]
Enable a "dark mode" button for Freewallet - I know there is a "theme" portion already being worked on. 

PLZ HELP MY EYES **bleeds from eyes**

Custom images for different sections or nodes or tabs of freewallet would be really fun and people would definitely show them off on social media when they customize them. That would be good for new users to be attracted to use Freewallet imo. Custom is fun.

**Comment by jdogresorg** [comment]
Please move to discussions section as an idea.
