### ISSUE TITLE
Show ALL Open Orders Tab

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#149]
After setting up many orders on the DEx, it can take some time to track, cancel and see all of an address's orders in one place. 

Is it possible to add a new button at the top somewhere within the Market Tab for "Open Orders" that could include sorting, tracking, and cancelling all open orders on the DEx (similar to Open Dispensers Tab).

**Comment by jdogresorg** [comment]
Please move to discussions section as an idea.
