### ISSUE TITLE
Low fee warning

### ISSUE THREAD

**Issue by jdogresorg** [jdogresorg/freewallet-desktop#15]
Need to alert a user whenever their tx fee is below the minimum relay fee (currently 0.00001000) and notify them that the transaction will NOT show up on many block explorers until the transaction is mined due to the low fee.

Make the alert optional so that users can disable it if they don't want to keep getting notified of low fee transactions.

**Comment by davestaxcp** [comment]
I deeper explanation of fee's and a link to the future FAQ might help regarding this: https://gist.github.com/davestaxcp/1e2cc086a13c9a2d045876852b57e5be#what-btc-fee-should-i-use

**Comment by jdogresorg** [comment]
Feel this feature is unnecessary at this time because :

- Currently enforce minimum tx fee of 1000 sats, which *currently* is well above any minimum relay fee for most transactions.  
- We are now seeing transactions at 1 sat/vb relayed for many months at a time
- If a transaction is broadcast with a fee lower tha minimum relay fee, the transaction will be rejected and alert the user to the issue
