### ISSUE TITLE
Fee issues, sat/vb, "high" setting and Freewallet not showing UTXO info

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#153]
I have been reviewing the issues coming in for users on the Freewallet Telegram (https://t.me/freewallet_io) and I have noticed a big discrepancy between new users and knowledge of UTXO's, how the "high" fee is being calculated and sat/vb on a specific fee. Myself included.

I can give you an example from my own experience:

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/975f4daf-f416-444f-a332-7f10d3f0ef4c)

The first send was just for sending an XCP asset to another address.

The second send was sending ALL of my BTC (lots of UTXO's) to an exchange address.

Despite Freewallet saying this "total btc fee" should be enough, Freewallet did not take into account how many UTXO's had to be sent and thus with the same btc fee amount (0.00004) was 1/3 of the sat/vb

Despite many people in this scene being knowledgeable of these specific small hiccups that may happen, in my experience 90% of the users don't know why their fee "came out too low" and it just "doesn't work." And just telling them to select "high" fee is not enough direction or education provided for them to get their transaction done in a reasonable amount of time. If you do not show an option or explanation on why it will be a higher fee, and they use "high" fee and it isnt high enough, in their experience the "high" setting would be broken.

- I think it's really important Freewallet shows not a "total btc amount" but the "full amount of btc for all UTXO's." Making this known when sending BTC especially is needed (most people are sending payment to a dispenser of exchange address in this scenario and need it done FAST). I see on the xchain API there is an option for showing an addreses' UTXO's. Could that be integrated here to show for each address on Freewallet? Basically a UTXO dust fee generator of sorts?

- I think it's important for people to know the "total btc amount" to sat/vb conversion as this number can be vastly different if sending all the btc on your address vs. sending 1 xcp token, vs. doing a 300+ multisend.... It should be very accurate and "work" every time from a user perspective when selecting "high." Even if its required to be expensive by the BTC network, I would rank getting the transaction done higher than importance of 'saving a buck on a fee.' This has already been mentioned as described here: https://github.com/jdogresorg/freewallet-desktop/issues/12, but I think it can be explained or displayed in a more "dumb user friendly" fashion.... People wont necessarily care how much it costs if its known by the user to be very accurate.

- Another aspect of trying to write a tutorial for CPFP using Freewallet (here: https://gist.github.com/davestaxcp/1e2cc086a13c9a2d045876852b57e5be#help-i-used-too-small-of-a-fee-and-my-transaction-is-not-confirming), is the plain fact users just will use Electrum because they can be using CPFP and picking the specific previous (parent tx) transaction. It would be very nice to either have Freewallet automatically try to use the previous unconfirmed transaction UTXO when doing the next transaction. Or simply having a "UTXO" list for each address to pick from when trying to do CPFP on Freewallet. Maybe even add a CPFP button on freewallet to somehow automatically do this?

- Another good "button" or "function" to have would be Consolidating UTXO's. It would be so extremely helpful for Freewallet to show, explain and offer a way to fix this all in the User Interface itself. It can link to FAQ's and more information, but it would solve a hell of alot of issues related to all of these errors: https://gist.github.com/davestaxcp/1e2cc086a13c9a2d045876852b57e5be#failure-to-send-not-enough-btc-in-wallet

**Comment by jdogresorg** [comment]
please only open github issues for actual technical issues, not for suggestions or feature requests, that belongs in the "Discussions" section.
