### ISSUE TITLE
Show sat/vB and allow user to set fee rate

### ISSUE THREAD

**Issue by BTCAlchemist** [jdogresorg/freewallet-desktop#155]
People often want to set the fee rate in sat/vB to know how quickly their transaction would confirm and how expensive it is relative to other transactions (regardless of # UTXOs used). The fee rates are shown in BTC and $ but not in sat/vB. Could you add sat/vB display for the fee and allow the user to set a custom sat/vB?

<img width="574" alt="image" src="https://github.com/jdogresorg/freewallet-desktop/assets/56145569/5445e0a1-2f32-4b33-85af-9b654963d38d">

**Comment by jdogresorg** [comment]
Please only open github issues for actual technical issues, not for suggestions or feature requests that belong in the "Discussions" section.

Please repost your request in the discussions section and it will get addressed eventually. 

I do have plans to update the fee system in freewallet-desktop, and already have "issues" open to add this feature.
