### ISSUE TITLE
Issuance Fee is ignored

### ISSUE THREAD

**Issue by SN-Noop** [jdogresorg/freewallet-desktop#166]
Final tx for issuance always use 0 for tx fee.

Using local version of FW with master.

When clicking on "Create Token" we can see this request sent to CP:
<img width="215" alt="image" src="https://github.com/jdogresorg/freewallet-desktop/assets/143439852/5e20a749-7359-4f25-8209-932cb6247532">

When clicking on "Yes" in confirm issuance we see this request:
<img width="213" alt="image" src="https://github.com/jdogresorg/freewallet-desktop/assets/143439852/94feedb5-ff91-42d1-8696-7d7a8cec60ab">

Second request is indeed the one signed and broadcasted.

In red, the fee for the first request used for estimation, value in sats. In blue the fee effectively used for the final TX, value in BTC => As createIssuance do parseInt on fee parameter, you get parseInt('0.00xxx') which results to zero.

<img width="925" alt="image" src="https://github.com/jdogresorg/freewallet-desktop/assets/143439852/d62bb46c-aab6-4380-8d5c-b89febe8531d">

**Comment by jdogresorg** [comment]
can confirm this is an issue, and it seems CP is just using default fee if 0 is passed as `fee`

Thank you for reporting this issue.  I will fix in next release.

**Comment by jdogresorg** [comment]
fixed in [v0.9.24](https://github.com/jdogresorg/freewallet-desktop/releases/tag/v0.9.24) release
