### ISSUE TITLE
Token description change charging x9 proposed fee

### ISSUE THREAD

**Issue by adm0dum** [jdogresorg/freewallet-desktop#168]
Everytime I change a token description I have the fee set to low (as it always is) and then somehow it charges me x6 of that. Every other function uses the fee that is set (low) except changing token description. Not the first time this has happened
![Freewallet Issue Screen Shot](https://github.com/jdogresorg/freewallet-desktop/assets/145166737/ae9ba183-5b19-4db2-9538-e87aa6edd939)

**Comment by jdogresorg** [comment]
Changing asset description to a longer description usually requires encoding the data via multisig, which requires additional btc fees to r code the data.Make sure you’re on the latest version of freewallet, where data encoding costs are confirmed with the user BEFORE broadcasting the transaction…. Freewallet has no hidden fees and all spending of btc is co formed with the user.Sent from my iPhoneOn Sep 15, 2023, at 3:18 PM, adm0dum ***@***.***> wrote:﻿
Everytime I change a token description I have the fee set to low (as it always is) and then somehow it charges me x6 of that. Every other function uses the fee that is set (low) except changing token description.

**Comment by davestaxcp** [comment]
adm0dum was on 0.9.23 which was the most recent version 3 days ago.
