### ISSUE TITLE
Replace-By-Fee (RBF) support

### ISSUE THREAD

**Issue by jdogresorg** [jdogresorg/freewallet-desktop#18]
Would be nice to have RBF support in the wallet and have a simple solution available for users who complain about their transactions being pending.

https://medium.com/@overtorment/bitcoin-replace-by-fee-guide-e10032f9a93f

**Comment by davestaxcp** [comment]
This could be nice but I think deeper explanation and education of fee's could be more helpful. Though if explained correctly and thoroughly to a new BTC user and the feature is added, could be a huge help for people accidently using a low fee.

**Comment by jdogresorg** [comment]
I believe support for RBF should be added on the protocol level (Counterparty) first to support RBF in transactions. Once this happens, will revisit integrating RBF support into FreeWallet.
