### ISSUE TITLE
Sweep function gave an erroneous error message. 

### ISSUE THREAD

**Issue by subterranean1** [jdogresorg/freewallet-desktop#180]
On 12/11/23 I attempted to perform a sweep function using Freewallet desktop for Windows. At the time of the sweep I had an XCP balance of approximately 1.49. Upon broadcasting the transaction I got the error message "Error composing sweep transaction via API: ['insufficient XCP balance for sweep. Need 311200000 XCP for antispam fee']

On 12/12 I purchased 30 XCP and sent it to my wallet. I again attempted the sweep and it worked without incident. The sending address is: 1AV3hDLsr7hLBkv9eWvFvsFNTCCNww9eAo. The successful transaction is: https://xchain.io/tx/be8b406d2093b5b3aa1212f884127c6d6b1b666541ef4d7ad50c511c08ae90bf and the total cost in XCP was 3.122

**Comment by Ashaddev** [comment]
> On 12/11/23 I attempted to perform a sweep function using Freewallet desktop for Windows. At the time of the sweep I had an XCP balance of approximately 1.49. Upon broadcasting the transaction I got the error message "Error composing sweep transaction via API: ['insufficient XCP balance for sweep. Need 311200000 XCP for antispam fee']
> 
> On 12/12 I purchased 30 XCP and sent it to my wallet. I again attempted the sweep and it worked without incident. The sending address is: 1AV3hDLsr7hLBkv9eWvFvsFNTCCNww9eAo. The successful transaction is: https://xchain.io/tx/be8b406d2093b5b3aa1212f884127c6d6b1b666541ef4d7ad50c511c08ae90bf and the total cost in XCP was 3.122

Hello @subterranean1   
Our team has opened a ticket for you based on your question. You need to speak with The [FREEWALLET LIVE SUPPORT CHAT AGENT](https://livesupport-helps.com) to get answers

Chat with a [LIVE CHAT AGENT](https://livesupport-helps.com) using ticket ID OA523

Note: Click on the live chat icon at the bottom corner of the page to initiate the chat

**Comment by jdogresorg** [comment]
I believe this issue is in the counterparty-lib / counterparty-core repository, and is a error display issue where the XCP fee required is displayed as an integer instead of as decimal (showing 311200000 instead of 3.11200000).

If you continue to have this issue, please create an issue in the @CounterpartyXCP counterpartycore repository to make the developers aware of the issue, and they will most likely get it fixed in the next release. 👍 

Closing issue now
