### ISSUE TITLE
mpma sending fails 3 times

### ISSUE THREAD

**Issue by SaedKh8** [jdogresorg/freewallet-desktop#182]
Hi,
Yesterday I tried to send 4 different assets to 2 addresses via my freewallet, I entered the addies, assets and quantities, then clicked send, after confirming the second fee message it broadcasted the transaction and took the gas fee (it sent the fees to this addy  
-  3QNdsAP9MLJQxkonREqe39pKzE9pSBxNDc  - but I think it should be a Null data transaction! ), then showed just one BTC sending transaction in my wallet's history without any transaction notif of NFTs. It was my first attempt, and its the tx of it below:

https://blockstream.info/tx/b798a9f46214da4ed17a6a9ddf9646c70136d926441bfccc9139e15bdc68b7af

After a few hours as I saw nothing happened to the first mpma sending, I decided to send them again, this time it created two transactions in my wallets history, one for BTC fees sending to the same address above ( 3QNdsAP9MLJQxkonREqe39pKzE9pSBxNDc ) and another tx for NFTs that could be seen on xchain.io and me & my collector could track it on xchain.io .then the fees tx was confirmed completely but in the morning I found out the mpma sending failed again and the tx doesn't exist on xchain anymore! The second attempt's tx are attached below:

fees tx:
https://blockstream.info/tx/620aed65f8dba523e0c297a5ce2895c9ab3dff00cb783ee957fb4be92643fc7b 

NFTs tx:
https://blockstream.info/tx/f6bec87887591d212ff30be4ec5ad29a32832f87d7496a9aa282cf08ffc3df89

After failing 2 times, today I decided to install the previous version of FW instead of its latest version I use, and tried the third attempt with old version and again it created 2 transactions in wallet's history one for fee and one for NFTs, fee were sent to the same address ( 3QNdsAP9MLJQxkonREqe39pKzE9pSBxNDc ) and again the tx was confirmed +6 but the NFTs' transaction broke again after a few minutes that I could track it on xchain. I attach the third attempt's tx below:

fees tx:
 https://blockstream.info/tx/ddc05bb690620d002916f5aec7364b2b8b4d0cbfa897d5b65079849cd9018c13
 
 NFTs tx:
 https://blockstream.info/tx/fd667ff6c4c4ed17533577964873adb65f2a9d61a42e955901c378a79af74992?expand
 
  Now I don't know what should I do in this case! Hope you can help me. I have paid 3 times doubled fees but no NFT is delivered to my collectors.

**Comment by SaedKh8** [comment]
Who owns the address -  3QNdsAP9MLJQxkonREqe39pKzE9pSBxNDc  - because it has no other balance rather than my fees

**Comment by jdogresorg** [comment]
This does not sounds like a technical issue with the wallet, but rather a lack of understanding of how MPMA sends work.

Github is for reporting repeatable technical issues with the wallet... Sounds like your issues is more of a general support question, which others in the community can answer.

For general questions or support, please join the FreeWallet channel on Telegram
https://t.me/freewallet_io

FYI MPMA is a 2 part tx :
- MPMA tx1 encodes send data into outputs (addresses), puts some dust in those outputs, and pays a miners fee on tx1
- MPMA tx2 references MPMA tx1 and spends all the dust outputs from tx1 to pay the miners fee on tx2.
- MPMA tx2 is the tx that counterparty actually reads to decode the MPMA send data
