### ISSUE TITLE
subasset minting + description using high fee v0.9.27

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#186]
tested minting a subasset with a description (easyasset):

https://zdxtxmklf4usl3suag6oflslt4qatx6vzf3gpg33aujlb7lifsba.arweave.net/yO87sUsvKSXuVAG84q5LnyAJ39XJdmebewUSsP1oLII/PEPEA.json

 - high fee setting was too low
 - 1 input on address
 
 first time I tried I used the same process to create a token, chose subasset, put all the right inputs in....
 
  though the tx it came out with looked way too low for a tx with a description but tested what it showed me anyway ($1.46 in fee's):
 
 - https://blockstream.info/tx/9d58e20dce0900aefdfe319a141560e48e20ff7a8dbb89ca4bec06e7d414ff4f
 
 - https://mempool.space/tx/9d58e20dce0900aefdfe319a141560e48e20ff7a8dbb89ca4bec06e7d414ff4f
 
 this first tx fee rate was 14.7 sat/vb but mempool dot space doesnt show the 'effective fee rate' on this transaction
 
![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/8ecf8dd0-ff78-4518-a172-068172e3f160)

 
 
 Second time looking through the UI I tried again and clicked around and realized I had clicked Named Asset and not Subasset
 but this was after I clicked the "Create Token" button....
 
...but I saw Freewallet say "Calculating Fees" in the bottom left and it changed the fee to about $6.00 (around 13,000 sats) and that seemed more likely to be enough (though it may be better to add a "calculate fee's button" and not have the "Create Token" button initiate that function)... 

- also it is strange for the first try it the program did not automatically update the fee, but seems to do it when i closed and reopened the program

Anyway, I upped the 'high' fee slightly to an even higher 14000 sats and tried it out

https://mempool.space/tx/4e9370ba787d8bb7a1a1312167996d5f6cc59d7797972902e1e1f602e89597b5

- tx was as 21.6 sat/vb

- but the effective fee rate came out as 8.64 sat/vb

- the tx came out with 5 outputs

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/85044498-b6e6-4906-8149-47dc66825437)

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/c83a2600-c200-46be-89e8-20db412fea4b)

so it looks like it wont be mined for a long while even setting a slightly higher fee than the calculated high setting 

https://blockstream.info/tx/4e9370ba787d8bb7a1a1312167996d5f6cc59d7797972902e1e1f602e89597b5

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/53a4b920-c265-4bd7-99b6-7f1fcc9907d4)

- high priority at same time was 26 sat/vb

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/5afccfa3-bd08-458d-b409-d1c017986d56)

but a few blocks later a fee rate of 21 sat/vb would have been fine

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/b01ae2b8-cb1a-4db3-a369-a3f4c44dc806)

just looks like the 'effective fee rate' is not high enough for the mempool

---

so I thought... hmm what about separate the minting and the description addition? so I closed and reopened Freewallet

and when I got to the fee setting and clicked "Create Token" it did not show a short 'Calculating Fee's' process and I closed and reopened again just to make sure... but I assumed, maybe since it is less outputs for this function it is less...

here's a test for minting the subasset without the description:

https://mempool.space/tx/28637e4b076e7d3a63a33fa0f80a48c17be9fdbab88a98974d8f4a906cd05b5a

https://blockstream.info/tx/28637e4b076e7d3a63a33fa0f80a48c17be9fdbab88a98974d8f4a906cd05b5a

- 15.6 sat/vb

- 9.57 sat/vb effective fee rate

- 2 outputs

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/0c3d1768-5983-483c-97a5-46edcb598052)

using
v0.9.27

**Comment by jdogresorg** [comment]
should be fixed now latest 0.9.27 binaries at https://github.com/jdogresorg/freewallet-desktop/releases/tag/v0.9.27
