### ISSUE TITLE
testing fee functions on 0.9.27 (second binary)

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#187]
here are some tx tests with the new binary from 0.9.27

first I tried to do a Subasset mint with an easyasset longform description (same details as in previous issue #186 but have 2 tx's stuck from yesterday on that same address..... still 1 input though because none were confirmed)

fee amount for subasset mint plus description was calculated in wallet and looked to be about $6 before the extra encoding fee (from the popup window FW shows)

sent tx through but almost no nodes see it:

https://xchain.io/tx/3f98cb0b284025bf3c808ec6f03b9546acce4e64cf24e47f19627e24bbb85633
https://mempool.space/tx/3f98cb0b284025bf3c808ec6f03b9546acce4e64cf24e47f19627e24bbb85633
https://live.blockcypher.com/btc/tx/3f98cb0b284025bf3c808ec6f03b9546acce4e64cf24e47f19627e24bbb85633/
^ it is visible on blockcypher but looks like too low of a fee (correct outputs though etc)

next I thought, okay why not just send some BTC and an asset to a new address and go from there (maybe make some dispensers for some cards I've been meaning to sell)

First I send about $10 in BTC to a new address and it showed me about a $3 fee:
https://mempool.space/tx/aeea2f8cb969ee818ac28c92179d06d9338234403a2e2f4e552c25ea79e9e70e
https://live.blockcypher.com/btc/tx/aeea2f8cb969ee818ac28c92179d06d9338234403a2e2f4e552c25ea79e9e70e/

too low of a fee / not all nodes seeing it....

then I sent a simple send of the card I want to sell (MELONCOCO):
https://xchain.io/tx/54f422f730e2da96a4bed84be0e1043ff37ac09d0dee9f7b95b90b9f67703e9f
https://blockstream.info/tx/54f422f730e2da96a4bed84be0e1043ff37ac09d0dee9f7b95b90b9f67703e9f
https://mempool.space/tx/54f422f730e2da96a4bed84be0e1043ff37ac09d0dee9f7b95b90b9f67703e9f
https://live.blockcypher.com/btc/tx/54f422f730e2da96a4bed84be0e1043ff37ac09d0dee9f7b95b90b9f67703e9f/

this is the only one that shows on xchain and blockcypher... but again - too low of fee and all seem to be stuck in limbo

can't seem to get anything done with recommended 'high' setting :(

**Comment by davestaxcp** [comment]
update - looks like the BTC send and single XCP asset send went through fine - was just super confusing to see nodes not see it for like 30 min from the other block explorers

but subasset mint not visible still

and unconfirmed tx's from yesterday were replaced/dropped

**Comment by jdogresorg** [comment]
fixed in 0.9.28
