### ISSUE TITLE
UI for Multi-Send not showing Transaction Link

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#188]
0.9.27

user broadcasts a Multi-send and usually the UI (for all other functions) shows a "Check Transaction on...." popup

but new version only shows:

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/4054db5f-0112-4f89-a8fa-2ff774b80674)

does not show link to tx

**Comment by jdogresorg** [comment]
fixed in 0.9.28
