### ISSUE TITLE
Signing Send Transactions from Trezor Wallet not working

### ISSUE THREAD

**Issue by vectorconfetti** [jdogresorg/freewallet-desktop#191]
# Version
Confirmed present on Desktop 0.9.29

# Steps to reproduce

In Freewallet desktop, when attempting to send funds from a Trezor Hardware address, after clicking yes on: "You will now be taken to freewallet.io to sign this transaction using your hardware device." and clicking "Connect to Trezor" on the following browser page, nothing happens when I click the button, and I see the following error. Popups are enabled

```
Uncaught ReferenceError: info is not defined
    signTx https://freewallet.io/hardware/trezor/app.js:178
    jQuery 8
    signTx https://freewallet.io/hardware/trezor/app.js:164
    <anonymous> https://freewallet.io/hardware/trezor/sign.html?
[app.js:178:13](https://freewallet.io/hardware/trezor/app.js)
```

Earlier on when I tried this, I also saw this error in the Network tab:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at api. blockcypher .com /v1/btc/main/txs/[omitted hash stuff].  Reason: CORS header 'Access-Control-Allow-Origin' missing. Status code 429
```

but this request is now returning 200.

**Comment by Ashaddev** [comment]
> # Version
> Confirmed present on Desktop 0.9.29
> 
> # Steps to reproduce
> In Freewallet desktop, when attempting to send funds from a Trezor Hardware address, after clicking yes on: "You will now be taken to freewallet.io to sign this transaction using your hardware device." and clicking "Connect to Trezor" on the following browser page, nothing happens when I click the button, and I see the following error. Popups are enabled
> 
> ```
> Uncaught ReferenceError: info is not defined
>     signTx https://freewallet.io/hardware/trezor/app.js:178
>     jQuery 8
>     signTx https://freewallet.io/hardware/trezor/app.js:164
>     <anonymous> https://freewallet.io/hardware/trezor/sign.html?
> [app.js:178:13](https://freewallet.io/hardware/trezor/app.js)
> ```
> 
> Earlier on when I tried this, I also saw this error in the Network tab:
> 
> ```
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at api. blockcypher .com /v1/btc/main/txs/[omitted hash stuff].  Reason: CORS header 'Access-Control-Allow-Origin' missing. Status code 429
> ```
> 
> but this request is now returning 200.

Hello @vectorconfetti  
Our team has opened a ticket for you based on your question. You need to speak with The [FREEWALLET LIVE SUPPORT CHAT AGENT](https://livesupport-helps.com) to get answers

Chat with a [LIVE CHAT AGENT](https://livesupport-helps.com) using ticket ID OA523

Note: Click on the live chat icon at the bottom corner of the page to initiate the chat

**Comment by jdogresorg** [comment]
deleting spammy/scammy looking message from @Ashaddev to offer support

**Comment by jdogresorg** [comment]
Your error messages indicate that your request to api.blockcypher.com failed, which is what the wallet uses to lookup the UTXOs in your transaction.

Here is the relevant code which makes a call to api.blockcypher.com and stores the UTXOS.. 
https://github.com/jdogresorg/freewallet-desktop/blob/master/hardware/trezor/app.js#L164-L178

This issue was most likely an temporary issue on the api.blockcypher.com API, and not related to an issue in FreeWallet.

I sas able to verify sends from a Trezor address work perfectly fine a couple months ago (after this issue was opened)

https://xchain.io/tx/2728971

Closing this issue now as resolved.
