### ISSUE TITLE
Dispenser data not being shown on xchain (not loading for users)

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#198]
recently a user mentioned in the FW TG chat:

Hey fam
Recently I can't see any information in my dispensers' pages, can anyone check them and is it possible that the dispenser addresses expire?! 🧐

PRAYFORPEACE
https://xchain.io/tx/17d4fc4531b15919d1c8b1e61e8d5d0f82eb25d99f03dd1792164e8c7df54302

FAKEILLUSION 
https://xchain.io/tx/ae33e630ebfcaef6ac7b3991de03391670995d1a168a681c197ca9a3ac214afc

FEARLESSFAM
https://xchain.io/tx/c6e260ba4a096bad2ba3f1ebfc18c8de7e6b1b50bea6a4fd155e022e3e33d51a

in which I looked up one of my own dispensers and I am getting the same issue:

I am getting the same issue when looking up my dispensers as well:

https://xchain.io/tx/914355f395352c7577e4ad48cc0701c0df8937d149ce1dee40b02f8e9f83fb25

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/66e0808b-2d71-4dd6-a4bc-81092b255b6b)

 you can still see the Dispenser information is live on the Counterparty side of things by looking it up on xcp.dev or xcp.io - for example here is my dispenser i linked above shown on xcp.io :

https://www.xcp.io/tx/914355f395352c7577e4ad48cc0701c0df8937d149ce1dee40b02f8e9f83fb25

and on xcp.dev:

https://www.xcp.dev/tx/914355f395352c7577e4ad48cc0701c0df8937d149ce1dee40b02f8e9f83fb25

---

weirdly enough, this Dispenser (for FAKEFREEDOM) still shows on Freewallet Desktop:

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/602f4163-307d-44df-bf41-28ecc62f45f8)

**Comment by jdogresorg** [comment]
Tracked issue down to a failing SQL query due to missing origin_ids

ran counterparty2mysql/misc/fix/fix_dispenser_origins.php script to update database

![telegram-cloud-photo-size-4-5860743095031804782-x](https://github.com/jdogresorg/freewallet-desktop/assets/376028/21ca321b-4386-4775-acf1-33698a7abb9d)

Should be good to go now
