### ISSUE TITLE
minimum BTC order

### ISSUE THREAD

**Issue by jdogresorg** [jdogresorg/freewallet-desktop#2]
It seems the minimum BTC order amount is 0.001 BTC. Update order interface to throw error if BTC buy or sell amount is less than 0.001.

https://github.com/CounterpartyXCP/counterparty-lib/blob/e875c45c586cc4fc840a59540a6d44bd03ee698b/counterpartylib/lib/messages/order.py#L436

We want to avoid wasted fees on orders like this https://xchain.io/tx/1489623

**Comment by jdogresorg** [comment]
Verified working in both directions including when market is flipped

![image](https://user-images.githubusercontent.com/376028/101834860-bdbff200-3aef-11eb-84b0-cf3e4463682d.png)
![image](https://user-images.githubusercontent.com/376028/101834873-c31d3c80-3aef-11eb-9984-46e199265e33.png)

**Comment by Washitawbadger329** [comment]
call me 3862692919

**Comment by jdogresorg** [comment]
I don't do voice calls. If you have an issue, please put the details in this ticket.
