### ISSUE TITLE
Data Table Automatically Redrawing when Sorting by Price

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#202]
Issue when sorting Dispenser and XCP DEx data tables reported amongst users as follows:

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/9ae24e4e-1377-4847-badb-1f68b7f901b6)

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/4136d788-0276-40ff-82dc-1b85c5936f7d)

Jdog responded saying:

![image](https://github.com/jdogresorg/freewallet-desktop/assets/136373423/fe993713-3116-403c-a6d1-7e90bdfdd246)

**Comment by jdogresorg** [comment]
Exchange and Dispensers datatables now save the preferred sorting order and restore the order when tables load.

Fixed with commit b4b12ab7a55a6695c7ae5691a51d5daf1cbf4212

Will be in next release of Freewallet in a few days
