### ISSUE TITLE
Multisend issue with fee handling, size of both transactions not accounted for

### ISSUE THREAD

**Issue by MiroslavJawgotzschjawa** [jdogresorg/freewallet-desktop#204]
When doing a Multisend there are 2 transactions. The first always has around 220vB, the second has more because of the data, maybe 700vB.

Freewallet now calculates and shows the fee of the whole 920vB of both transactions which is correct but then it just uses the same fee of fee*920 for both transactions and fw does not account for the size of both transactions when calculating fees. 

As a result the first transaction fee is overpaid and the second transaction fee is slightly overpaid because of the extra 220vB.

It do not know if this has to be this way because of Counterparty.

**Comment by jdogresorg** [comment]
Thank you for reporting this issue. Counteparty 2.0 has now disabled `p2sh` encoding and only supports the more expensive `multisig`, so this is no longer an issue, as the whole MPMA send happens in a single transaction instead of two, so the fee estimates should be much better.
