### ISSUE TITLE
 being able to close dispensers from "origin" address

### ISSUE THREAD

**Issue by tweetious** [jdogresorg/freewallet-desktop#208]
When trying to close a dispenser from the "origin" address ("Main Menu->Close dispenser"), I am receiving the message: “Transaction hash points to a dispenser on a different address!”

Thank you in advance, I much appreciate all your efforts!!! :-)

Edit: The issue was discussed at the Freewallet telegram chat, and was proposed to create a github issue. I have also many open dispenses and it would be REALLY helpful to be able to close all of them directly from the "origin" address, rather than from the "source" address. Thanks again!

**Comment by jdogresorg** [comment]
fixed with commit 7a4497fc61911a39a8dc0e95f565870971a6de9b

Will be in the next freewallet-desktop release in a day or two
