### ISSUE TITLE
Problem with not displaying the contents of wallet

### ISSUE THREAD

**Issue by LordAntHreX** [jdogresorg/freewallet-desktop#228]
![image](https://github.com/user-attachments/assets/9fcc9b68-86db-470b-a239-0e4cb118f479)
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

https://tokenscan.io/address/1MoZ3P9jcLFHuRU2L8jLgGqsG8gBnY111j

When I want to view balances of my wallet on tokenscan this error comes and is not letting me see the assets in the wallet. The problem appears to be some asset on the page 6 if the site is showing 10 lines per page. If the site is set to 100 the error message is there right away.

**Comment by Susankaten** [comment]
> ![image](https://private-user-images.githubusercontent.com/140816036/391985398-9fcc9b68-86db-470b-a239-0e4cb118f479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzM0ODAsIm5iZiI6MTczMzIzMzE4MCwicGF0aCI6Ii8xNDA4MTYwMzYvMzkxOTg1Mzk4LTlmY2M5YjY4LTg2ZGItNDcwYi1hMjM5LTBlNGNiMTE4ZjQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMzM5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzg2ZjlhZmY1ODM2YmRkNWViMGY2OGE4MDE0YWU5ZTU4M2EzZDU5Mzc5NmVjMmRhYzVkMzQzNmU0NGZhNjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OdhuSOkVdIXkaLCWzoXteV7-m-Tb_jWp7fBQEUvK8Sg) DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
> 
> https://tokenscan.io/address/1MoZ3P9jcLFHuRU2L8jLgGqsG8gBnY111j
> 
> When I want to view balances of my wallet on tokenscan this error comes and is not letting me see the assets in the wallet. The problem appears to be some asset on the page 6 if the site is showing 10 lines per page. If the site is set to 100 the error message is there right away.


Hello @LordAntHreX 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID TON18912
Please see the link below to our dedicated support line:
[Tokenscan  DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by swissDev-cloud** [comment]
> ![image](https://private-user-images.githubusercontent.com/140816036/391985398-9fcc9b68-86db-470b-a239-0e4cb118f479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzQwMDIsIm5iZiI6MTczMzIzMzcwMiwicGF0aCI6Ii8xNDA4MTYwMzYvMzkxOTg1Mzk4LTlmY2M5YjY4LTg2ZGItNDcwYi1hMjM5LTBlNGNiMTE4ZjQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMzQ4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmY0YmIzYzc4NmI0NGNiMmRkZjA1M2RhYTA0NjMyZTZiMzYzZDY1NGQ5M2NjYWQ4MTUzMWJiNzM3NWQ2N2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cTCG7xRJl-MwC5MgTOYsiZ9JZub8CjafAyQXITX0Hkw) DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
> 
> https://tokenscan.io/address/1MoZ3P9jcLFHuRU2L8jLgGqsG8gBnY111j
> 
> When I want to view balances of my wallet on tokenscan this error comes and is not letting me see the assets in the wallet. The problem appears to be some asset on the page 6 if the site is showing 10 lines per page. If the site is set to 100 the error message is there right away.
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Tokenscan Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by jdogresorg** [comment]
This issue should be fixed now. I reported the 2 above scammers and deleted their comments.
