### ISSUE TITLE
"Error while trying to sign send transaction"

### ISSUE THREAD

**Issue by Emily7777** [jdogresorg/freewallet-desktop#3]
I'm trying to send BCY & XCP.  When I click send, I get the error "Error while trying to sign send transaction".

I have tried over the last several days.  Still no luck.

I'm using 0.9.9,

Please advise.

**Comment by jdogresorg** [comment]
Can you please try again in the latest release of the wallet v0.9.10 and reopen this issue if your still having the signing problem.

https://github.com/jdogresorg/freewallet-desktop/releases/tag/v0.9.10
