### ISSUE TITLE
Download FreeWallet.exe - Where?

### ISSUE THREAD

**Issue by say168** [jdogresorg/freewallet-desktop#33]
Where to go to Download FreeWallet.exe?
I did a search for .exe file under code and was not able to locate.

**Comment by jdogresorg** [comment]
Try visiting the freewallet.io website and clicking the "Download for Windows" link which will take you directly to the github release page where you can download the .exe

https://github.com/jdogresorg/freewallet-desktop/releases

![image](https://user-images.githubusercontent.com/376028/92150513-5bf73a00-edd4-11ea-8652-12bde5a99bc5.png)
