### ISSUE TITLE
Old orders

### ISSUE THREAD

**Issue by ElvisDead** [jdogresorg/freewallet-desktop#35]
Cant cancel my old orders :)
![photo_2020-09-21_18-30-16](https://user-images.githubusercontent.com/71656308/93786968-96683000-fc38-11ea-98e8-c6b0708637ab.jpg)
![photo_2020-09-21_18-30-29](https://user-images.githubusercontent.com/71656308/93786976-98ca8a00-fc38-11ea-8368-1e2712b95c5d.jpg)

**Comment by jdogresorg** [comment]
Ticket already opened for this issue at #14
