### ISSUE TITLE
Highlight "official" FULLACCESS dispensers

### ISSUE THREAD

**Issue by evaarnas** [jdogresorg/freewallet-desktop#37]
In order to prevent confusion and detect possible frauds, the UI could highlight the FULLACCESS dispenser provided by Freewallet. (other options could still be shown, since somebody can offer a lower price for a "little used" tokens)

**Comment by jdogresorg** [comment]
Starting in version 0.9.16 the "Buy FULLACCESS" button in the "About" window takes a user directly to a dialog box which buys FULLACCESS from the official dispensers. Users still have the option of purchasing FULLACCESS tokens by looking for open FULLACCESS dispensers with lower prices.

Added in commit 2f4f9c1ddf8055262aee54ceeef144c2c0824bfc
