### ISSUE TITLE
Orders not showing

### ISSUE THREAD

**Issue by 2weiX** [jdogresorg/freewallet-desktop#51]
![image](https://user-images.githubusercontent.com/22128019/116656145-7944ce00-a98c-11eb-92fb-e0f8a287fd27.png)
![image](https://user-images.githubusercontent.com/22128019/116656155-7ea21880-a98c-11eb-81ce-c55780c9bcdb.png)

placed an order to SELL BACHELORPEPE
cannot cancel it because it doesn't show up on the "my open orders" in freewallet

**Comment by 2weiX** [comment]
https://xchain.io/tx/1559192

link to order

**Comment by jdogresorg** [comment]
Not sure why the order is not showing up in your "My Open Orders" tab... but you can also cancel any order by just entering the order transaction hash... Menu->Cancel Order

![image](https://user-images.githubusercontent.com/376028/116700372-8efdc780-a97b-11eb-8057-720d94ad9e12.png)

![image](https://user-images.githubusercontent.com/376028/116700386-9329e500-a97b-11eb-9c32-c623ce278f42.png)

**Comment by 2weiX** [comment]
nice!
would be sweet to have a overview of "all open orders" or something per address, too ;)
