### ISSUE TITLE
Markets not (re-) loading

### ISSUE THREAD

**Issue by 2weiX** [jdogresorg/freewallet-desktop#54]
![image](https://user-images.githubusercontent.com/22128019/119812493-7df79600-bee8-11eb-87f6-41d4c4b52bca.png)

only the first interaction with markets works, as soon as I have looked up one card, the next lookup will fail, markets screen will remain empty, also the deeplinking to the market doesn't have any effect

![image](https://user-images.githubusercontent.com/22128019/119812634-9ff11880-bee8-11eb-90e9-f84a9ceb0cac.png)

**Comment by 2weiX** [comment]
closing and reopening freewallet works for exactly one market, then fails again.

**Comment by 2weiX** [comment]
```
jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #RAREPEPE/XCP table.datatable
    at Function.se.error (jquery.min.js:2)
    at se.tokenize (jquery.min.js:2)
    at se.select (jquery.min.js:2)
    at Function.se [as find] (jquery.min.js:2)
    at S.fn.init.find (jquery.min.js:2)
    at new S.fn.init (jquery.min.js:2)
    at S (jquery.min.js:2)
    at updateMarketsView (freewallet-desktop.js:4792)
    at cb (freewallet-desktop.js:4750)
    at freewallet-desktop.js:4758
```


I can remove the RAREPEPE/XCP market, but when I close the app and/or navigate somewhere else, it's back again

**Comment by jdogresorg** [comment]
The Tabs are meant for you to enter a single asset, not a market pair... so you would enter "RAREPEPE" or "XCP" and a tab would appear showing you all the various assets which are trading against that pair.

I still see that there are some redraw issues with the datatables when refreshing, and will work on getting this fixed.
