### ISSUE TITLE
Create an alert in any dispenser when the token is being dispensed less than 1.0

### ISSUE THREAD

**Issue by whiterabbit1111** [jdogresorg/freewallet-desktop#56]
Eg.  There are a few times that someone has been setting up dispensers for PepeCash whereby it is being dispensed at the rate of .01 instead of 1.0.
This is easy for a buyer to miss (especially a noob) and therefore they get far less than what they believed they were paying for. 
Some sort of warning may assist here.
Thanks!
<img width="898" alt="PCash dispenser scam" src="https://user-images.githubusercontent.com/80554021/126021040-6d56e556-d752-445b-bd13-b18061760d36.PNG">

**Comment by jdogresorg** [comment]
added feature in commit 0fc5458
