### ISSUE TITLE
BTC price amount error results in unexpected amount

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet-desktop#59]
When creating a dispenser, and providing a fixed price, the resulting amount is sometimes slightly different that expected.

For example, a BTC amount of .009 is specified, but the resulting amount might be .0089999.  This creates a user experience issue, as some wallets will not sent the right amount, and there is a deficiency of 1 satoshi, resulting in the dispenser not being triggered.

Theoretically, the next user to send the remaining .00000001 would trigger the dispenser, and retrieve the asset.

**Comment by jdogresorg** [comment]
1.) need to fix amount/usd price when tabbing between the two (detect tab and prevent changes for 1 second)

2.) for dispensers, make sure that sent amount is at least the amount that the dispenser is requesting... or a multiple of it.

**Comment by masoud213** [comment]
Btc

**Comment by jdogresorg** [comment]
should be fixed in the next release :)
