### ISSUE TITLE
Wallet not recognizing UTXO

### ISSUE THREAD

**Issue by hcarpach** [jdogresorg/freewallet-desktop#60]
I've been having some trouble while sending BTC or other assets from FreeWallet Desktop. The wallet seems to be unable to recognize the UTXO in the wallet, so, for example, if I want to send 0.01 BTC, and I have 0.1 BTC, the wallet might throw an error that there's not enough money or that some of the coins I'm trying to spend are "unconfirmed", which is not the case (unless the wallet takes a certain number of confirmations as a "confirmed transaction").

For what I've been able to understand, the wallet has some trouble understanding (1) coins that come from a dispenser transaction and (2) UTXO that are simply too small, maybe some problem with the addition of decimals.

In the RarePepe Telegram group, people suggests sending more BTC to the address or sweeping the BTC from the private key using Electrum. Both are solutions to the problem, but create a terrible UX problem and a bigger security problem due to people needing to manipulate their seeds/private keys.

Here's an example of the error:

![2021-08-25 13 13 22](https://user-images.githubusercontent.com/34944340/130827316-f3682ba1-1ff5-456e-bb52-c8e8652d9973.jpg)

Hope this is useful.

**Comment by jdogresorg** [comment]
This is an issue in the core counterparty software that we are working on resolving in the next release.

https://github.com/CounterpartyXCP/counterparty-lib/issues/1126
