### ISSUE TITLE
import multiple private keys

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet-desktop#64]
Using the current method, a single private key can be imported.  Add a function that allows the user to paste in a list (delimited or just return-separated) to import multiple private keys in one operation.

**Comment by jdogresorg** [comment]
This issue should be addressed in commit b935614 and included in the next freewallet release.

![image](https://github.com/jdogresorg/freewallet-desktop/assets/376028/0f214873-7a10-41ab-aa32-41cdf833f912)
