### ISSUE TITLE
add multiple new addresses at once

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet-desktop#65]
The current operation is to "Add New Normal Address," after which a OK confirmation appears, and the address is generated.  Add another function which allows for user input to generate 5, 10, or 100 address in one click.

**Comment by jdogresorg** [comment]
This issue should be addressed in commit b935614 and released in the next release of Freewallet

![image](https://github.com/jdogresorg/freewallet-desktop/assets/376028/88c0bf9b-7454-4748-8ec7-e352f1c11b60)
![image](https://github.com/jdogresorg/freewallet-desktop/assets/376028/a14d8362-a587-4304-a3d1-ef63ea81e3ea)
![image](https://github.com/jdogresorg/freewallet-desktop/assets/376028/683052ab-1b5b-444a-9dd7-0b0bdf67e243)
![image](https://github.com/jdogresorg/freewallet-desktop/assets/376028/05e9f9fa-da1b-4c70-9d7a-4efedd388ab7)
