### ISSUE TITLE
number format in open trade order (native windows)

### ISSUE THREAD

**Issue by NicolasSierro** [jdogresorg/freewallet-desktop#7]
![image](https://user-images.githubusercontent.com/6316174/48882673-c287af80-ee1b-11e8-8773-2f57d5a9e3e8.png)

Numbers not so explicit with this format. I understand that mathematical it could be correct, but wouldn't be an alternative trying to have one of the paired asset be " 1 " or the number of units on sale (e.g. here " 5 ") ?

The transaction is https://xchain.io/tx/1378606 :
Buy Quantity | Sell Quantity
240  BITCRYSTALS  | 5 LATOMOO

**Comment by jdogresorg** [comment]
I believe this issue has been resolved in recent versions of FreeWallet and was related to the asset divisibility not being known and displaying a divisible asset quantity incorrectly.
