### ISSUE TITLE
Dispenser "Buy Now" sent 1 satoshi less than specified when buying one unit of give amount

### ISSUE THREAD

**Issue by LUCampus** [jdogresorg/freewallet-desktop#77]
I used the "Buy now" button to buy 1 xcp from a dispenser, with give amount 1 xcp, for 0.00029999 BTC.
Somehow there was sent 0.00029998 BTC and since it was 1 satoshi too little nothing was sent back to me.
I think it has something to do with the cost being specified to the 8th decimal. If the cost was 0.00029990 I think it would have sent 0.00029990. Some mathematical operation rounded off the last decimal.

When doing the same by using the send function in FreeWallet the correct amount was sent. 

I used the latest version of FreeWallet, 0.9.19.

https://www.blockchain.com/btc/tx/b846c1ef7dd811618742b47929b9f7b13ced8f9d22052ea6976cb118879650f4

**Comment by jdogresorg** [comment]
also some funkyness when creating dispensers to sell at a price of 0.00029999 as the dispenser is opened up at 0.00029998. Need to figure out where the rounding error is occurring and fix

**Comment by jdogresorg** [comment]
similar to issue #110 which has been fixed and will be included in the next release.
