### ISSUE TITLE
App won't open/run Win64 install

### ISSUE THREAD

**Issue by gaboychabela** [jdogresorg/freewallet-desktop#86]
Installed on a brand new pc with up to date OS windows10. I rebooted, installed & uninstalled with no result. 
Please advise. 
(Unable to run on mobile, phone has no room)

**Comment by bitpaint** [comment]
Do you have Chrome installed?
As well as Latest supported Visual C++ Redistributable ?
It's running fine here. There is no shortcut on the desktop so i go to  `C:\Program Files\FreeWallet` and click `FreeWallet.exe`
