### ISSUE TITLE
Must enter a valid Address

### ISSUE THREAD

**Issue by jcbacud** [jdogresorg/freewallet-desktop#90]
Hi,

I'm having this error on my account on freewallet, and I don't know the error about

![image](https://user-images.githubusercontent.com/49434753/162271896-76ddc772-c31c-47f7-8133-200108a9eb62.png)

I hope someone can answer me

**Comment by jdogresorg** [comment]
this is an error in freewallet MOBILE.... the error is because the address your trying to send to is not supported by the wallet (probably a bech32 segwit address).
